apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer   # AWS will create an ELB for you
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8081        # external port
      targetPort: 80
